### ISSUE TITLE
After Flashing Micropython...

### ISSUE THREAD

**Issue by JustDr00py** [varna9000/t-deck-lorawan-micropython#1]
Im having issues after flashing micropython. I can not see the files in Thonny did you have this issue?

**Comment by varna9000** [comment]
You have to manually upload the files from this repo, after you have flashed the micropython firmware. Don't forget to `mip install`  the lora sx1262 driver as well, since it's are not in the firmware which I mentioned in the Readme. 
I guess I should put these things in the readme.

**Comment by JustDr00py** [comment]
Im sorry for the misunderstanding when i flashed micropython. any version I tried the one you linked. As well as one i compiled from that repo. I could only get repl to show in thonny. the files were corrupt? what was the command you used to flash the T-Deck?

**Comment by JustDr00py** [comment]
Im not asking how to use micropython, I understand your files are not included in the firmware, but my issue is that I can not get the firmware successfully flashed?

**Comment by varna9000** [comment]
Use Thonny to flash it: 

1. Press and hold the trackball button of T-deck and plug the device into your computer. The computer will recognise the device as serial device.
2. In Thonny: Menu->Configure Interpreter-> Port or WebRepl, select the your COM port
3. Bottom right on the same dialog "Install or update Micropython"
4. Choose the firmware whch I linked in this repo

(Edit: don't forget to turn the switch  of T-deck on before step 1 )

I hope this helps.
